export const TestIDs = {
  HEADLINE_VIEW_CONTAINER: 'HEADLINE_VIEW_CONTAINER',
  TOP_STORIES_LIST: 'HEADLINE_VIEW_CONTAINER',
  HEADLINE_VIEW_LIST_ID: 'HEADLINE_VIEW_LIST_ID',
  HEADLINE_VIEW_LIST_ID_OPEN_URL: 'HEADLINE_VIEW_LIST_ID_OPEN_URL',
  HEADLINE_VIEW_LIST_SHARE: 'HEADLINE_VIEW_LIST_SHARE',
};
